version: '3.8'

services:
  db:
    image: postgres:13
    container_name: capacity-planning-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capacity_planning
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - capacity-planning-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: capacity-planning-backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/capacity_planning
      - LOAD_SAMPLE_DATA=true  # Set to false to start with an empty database
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - capacity-planning-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: capacity-planning-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - capacity-planning-network

networks:
  capacity-planning-network:
    external: false

volumes:
  postgres_data:
